### PR TITLE
multiple sub connector with array

### PR DESCRIPTION
**Pull request by neoera**
var options = [];
angular.forEach(question.options, function (option, key) {
var optionObj = {};
   optionObj.label = option.text;
   options.push(optionObj);
});

### CODE REVIEW

**Comment by sdrdis** [comment]
Thank you for the PR ! Just so you know, I have seen your pull request. I am just a bit under the water right now, so I will see this in the following days.

Thanks for your patience.

**Comment by sdrdis** [comment]
Sorry again for the late answer. Could you write here a full example? I am struggling in seeing what it is supposed to do...

**Comment by neoera** [comment]
Actually, i changed my own code. Previous solution was not helpful. But, this works. I share the solution with you.

                        var operatorData = {
					        type: 'SINGLE_SELECT_QUESTION',
					        id: response.id,
					        top: 60,
					        left: 500,
					        properties: {
					          	title: 'Question',
					          	clazz: 'ss-question-item',
					          	inputs: {
					            	in_1: {
					              		label: response.questionText,
					            	}
					          	}
					        }
					    };

setQuestionOptionsForOperator(response, operatorData);


function setQuestionOptionsForOperator (response, operatorData) {
			var options = [];
        	angular.forEach(response.options, function (option, key) {
		        var optionObj = {};
		        optionObj.label = option.text;
		        options.push(optionObj);
		    });

		    var outputs = {};
	      	for (var i = 0; i < options.length; i++) {
	      		outputs["out_"+(i+1)] = { ["label"]: options[i].label };
	      	}
            operatorData.properties.outputs = outputs;
		};


I added the outputs with for loop and i deleted the previous code i sent. I apologize for this.

**Comment by sdrdis** [comment]
Merged (with pull request from @ernaniaz). Thanks!

**Pull request closed without merging**
