### PR TITLE
Fix for issue #49

### PR DESCRIPTION
**Pull request by Elvaron**
This approach attempts to fix the issue #49, though I would welcome a review of the code submitted.
JavaScript isn't my strong suit.

### CODE REVIEW

**Comment by sdrdis** [comment]
Thanks ! Sorry, I am a bit busy at the moment, so it will take a few weeks so I can take a look at it.

**Comment by Elvaron** [comment]
No worries 👍

**Comment by rdenubila** [comment]
You saved my day @Elvaron, thank you!

**Comment by sdrdis** [comment]
Merged (with pull request from @ernaniaz). Thanks!

**Pull request closed without merging**
